# Generated by Django 3.1.3 on 2021-05-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210517_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_this_a_local_product',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
