# Generated by Django 3.1.3 on 2021-05-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_is_this_a_local_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_this_a_local_product', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
