# Generated by Django 3.1.3 on 2021-05-24 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210524_1113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Local',
            new_name='Local_Product',
        ),
    ]
