# Generated by Django 3.1.3 on 2021-05-24 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210524_1116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Local_Product',
            new_name='LocalProduct',
        ),
    ]
